# Generated by Django 5.0.3 on 2024-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_liked_post_number_of_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
