# Generated by Django 5.0.3 on 2024-03-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_rename_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
